[project]
name = "joky"
version = "0.1.0"
description = "Free jokes API"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pandas>=2.3.3",
    "quart>=0.20.0",
    "ruff>=0.14.9",
    "uvicorn[standard]>=0.38.0",
]
